### ISSUE TITLE
Support table of contents

### ISSUE THREAD

**Issue by dkager** [snaekobbi/pipeline-mod-dedicon#14]
- [x] A TOC is indicated by a heading "Inhoud band N", where N is the volume number.
- [x] A TOC is a list of items formatted as `title print-page braille-page`.
- [x] The first line of each item is negatively indented by 2.
- [ ] The last volume includes a TOC of all volumes except the last volume.

**Comment by bertfrees** [comment]
> - [x] A TOC is indicated by a heading "Inhoud band N", where N is the volume number.

Can be accomplished with the following CSS (not tested):

``` css
#generated-toc::-obfl-on-toc-start {
  display: block;
  content: 'Inhoud band ' -obfl-evaluate('(round $volume)');
}
```
