### ISSUE TITLE
Volume headings in document scope TOC

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-dedicon#41]
This can be done by applying a rule like the following to a TOC element (e.g. `#generated-document-toc`):

``` css
#generated-document-toc {
  display:-obfl-toc
}
#generated-document-toc::-obfl-on-volume-start {
  content: 'Band ' -obfl-evaluate('(round $started-volume-number)')
}
```
