### ISSUE TITLE
Print page range on first braille page does not include first print page

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-dedicon#49]
See test in [test_css_formatter.xprocspec](https://github.com/snaekobbi/pipeline-mod-dedicon/blob/eb84b61bd3994994c869d1a4a578ed1f340183aa/src/test/xprocspec/test_css_formatter.xprocspec#L56).

**Comment by bertfrees** [comment]
There are two separate issues:
1. The behavior of "page-start-except-last" is a bit unfortunate, but strictly speaking not a bug. To understand this let's consider the case where there is some content before the first page number ("2"). The page number range would still be the same ("4") and this would be a correct result according to the CSS:
   
   ``` css
   @top-center {
       content: string(print-page-from, page-start-except-last)
                string(print-page-to, page-last);
   }
   ```
   
   "page-start-except-last" is not defined in the spec yet but would be defined analogue to "[page-start](http://braillespecs.github.io/braille-css/master/index.html#dfn-string-start)":
   
   > a) The value of the first assignment on the page is used if the content box (fragment) of that element does not follow any other content boxes on the page.
   > b) Otherwise the assignment in effect at the end of the previous page (entry value) is used.
   
   It currently says nothing about the case when there are content boxes preceding the first assignment on the page and there is no entry value, so it results in the empty string, and not the first value on the page ("page-first").
2. The fact that "page-start" and "page-start-except-last" do not select "2" in the test is a bug. Notably the "a)" part of the definition is broken. This could (and should) be fixed directly, however if we would slightly change the meaning/behavior of "page-start" and "page-start-except-last" in order to solve issue 1, we also make issue 2 less of a problem.

---

Example input:

``` xml
<dtbook>
  <book>
    <bodymatter>
      <level1>
        <pagenum page="normal" id="p-2">2</pagenum>
        <h1>Hoofdstuk 1</h1>
        <p>Eerste alinea.</p>
        <pagenum page="normal" id="p-3">3</pagenum>
        <p>Tweede alinea.</p>
        <p>Derde
          <pagenum page="normal" id="p-4">4</pagenum>
          alinea.
        </p>
      </level1>
    </bodymatter>
  </book>
</dtbook>
```

and expected result:

```
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠼⠃⠀⠤⠀⠼⠙⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠼⠁
⠨⠓⠕⠕⠋⠙⠎⠞⠥⠅⠀⠼⠁

⠨⠑⠑⠗⠎⠞⠑⠀⠁⠇⠊⠝⠑⠁⠲
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠼⠉
⠨⠞⠺⠑⠑⠙⠑⠀⠁⠇⠊⠝⠑⠁⠲
⠨⠙⠑⠗⠙⠑
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠼⠙
⠁⠇⠊⠝⠑⠁⠲
```

**Comment by bertfrees** [comment]
https://github.com/daisy/pipeline-mod-braille/commit/463796fee19528d81856e9a553137f6ba346334a would fix it if it weren't for [this rule in dedicon-default.scss](https://github.com/snaekobbi/pipeline-mod-dedicon/blob/eb84b61bd3994994c869d1a4a578ed1f340183aa/src/main/resources/css/dedicon-default.scss#L143):

``` css
frontmatter, bodymatter, rearmatter {
    /* The following line sets the values used for the top-center page position and the TOC. */
    string-set: print-page-from '', print-page-to '', print-page-toc '';
}
```

@dkager: What exactly does this do?
